sonar.projectKey=mlaurajeronimo_prova03-e2e-MariaLaura2
sonar.organization=mlaurajeronimo
sonar.projectName=Playwright E2E
sonar.projectVersion=1.0
sonar.sources=src/support
sonar.tests=src/scenarios
sonar.test.inclusions=src/scenarios/**/*.spec.ts
sonar.exclusions=artifacts/**,node_modules/**
sonar.sourceEncoding=UTF-8
